### ISSUE TITLE
Element in iteration expect to have v-bind:key

### ISSUE THREAD

**Issue by hoaflee** [wxs77577/adminify#12]
I have the problem at src/components/Grib.vue
![image](https://user-images.githubusercontent.com/23038027/38799623-eb7aa2f4-419f-11e8-89b5-2097279d27dd.png)
In 2.2.0+, when using v-for with a component, a key is now required.
How to fix it? Thank you!
https://vuejs.org/v2/guide/list.html#range

**Comment by wxs77577** [comment]
Please check https://github.com/wxs77577/rest-admin

**Comment by hoaflee** [comment]
Thank you very much!
